version: '3.1'
services:
  web:
    build: ./GreetingsApp
    hostname: greetingsweb
    ports:
      - "5000:5000"
    environment:
      - BROKER=amqp://guest:guest@greetings_broker:5672
      - Database__Greetings=Server=greetings_db;Uid=root;Pwd=root;Database=Greetings
      - Database__GreetingsDb=Server=greetings_db;Uid=root;Pwd=root
      - Database__MessageStore=Server=greetings_db;Uid=root;Pwd=root;Database=Greetings
      - Database__MessageTableName=Messages
    links:
      - rabbit:greetings_broker
      - mysql:greetings_db
    depends_on:
      - rabbit
      - mysql
  worker:
    build: ./GreetingsWorker
    hostname: greetingsworker
    environment:
      - BROKER=amqp://guest:guest@greetings_broker:5672
      - Database__Greetings=Server=greetings_db;Uid=root;Pwd=root;Database=Greetings
      - Database__GreetingsDb=Server=greetings_db;Uid=root;Pwd=root
    links:
      - rabbit:greetings_broker
      - mysql:greetings_db
    depends_on:
      - rabbit
      - mysql
  rabbit:
    image: rabbitmq:3-management
    hostname: greetings_broker
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
  mysql:
    hostname: greetings_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')